apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: university-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: university-ns
spec:
  releaseName: university-dtg
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-indy/charts/indy-domain-genesis
    sourceRef:
      kind: GitRepository
      name: flux-bevel
      namespace: flux-bevel
  values:
    metadata:
      name: university-dtg
      namespace: university-ns
    organization:
      name: university
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"NLEsWTp7ASJgz6PJBMYs7V","role":"0","verkey":"CdLZz2nmKBZBmbX3wViiRuz2DjgPrTD5AhQbgaq9jJTo"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"T81AzAXJkw3gyYhQpVF2mz","role":"0","verkey":"FEjENMi4ZEkYKEq1SAREapFZi9PyctWrCKn5YXHyYsFb"},"metadata":{"from":"NLEsWTp7ASJgz6PJBMYs7V"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-1","dest":"NwYczLc1oAFBFLVqVPER4u","role":"2","verkey":"CxafPTK9gUKhf739DPQWksHQVfLEEsJNGiZsfW7T3fYq"},"metadata":{"from":"T81AzAXJkw3gyYhQpVF2mz"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-2","dest":"NXkiucV3vGM9bnu2yqHVkT","role":"2","verkey":"Cjca6MsH6KA4APkmwgCQkuGdKeJhsBMuNHvXsD7ztfWz"},"metadata":{"from":"T81AzAXJkw3gyYhQpVF2mz"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-3","dest":"9vaTtwGScVfiBXTKAFzK4G","role":"2","verkey":"5s6dRpjn37maMtTrkdFvWNr1iGdf89M7xUgZJKTbu6QA"},"metadata":{"from":"T81AzAXJkw3gyYhQpVF2mz"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-4","dest":"8gZRd8gjFZWvgF8yjYfN6o","role":"2","verkey":"5Bqzz8JeXmAAPbBZ3EpgvqsbzVWfQRtNc1mnCtLyY5WE"},"metadata":{"from":"T81AzAXJkw3gyYhQpVF2mz"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
