apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: university-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: university-ns
spec:
  releaseName: university-dtg
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-indy/charts/indy-domain-genesis
    sourceRef:
      kind: GitRepository
      name: flux-bevel
      namespace: flux-bevel
  values:
    metadata:
      name: university-dtg
      namespace: university-ns
    organization:
      name: university
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"ThX4fTkveq7RU2Ve6mnajS","role":"0","verkey":"FYzibVNzpdhk5fpk9NU13csKShggEuaiosFGtqTUJJHb"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"2H2kW5YB16Vtm8BL6MfU8G","role":"0","verkey":"hMEuNH1499iRhkgMu3JKo8YATxRTG6LarcsadSBayaS"},"metadata":{"from":"ThX4fTkveq7RU2Ve6mnajS"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-1","dest":"55M4HQWFT4X3gvLwQmwgW8","role":"2","verkey":"3DpMhCMna2ragweN7E7fJnNSJAw8x6nAULV6KK1gnBVQ"},"metadata":{"from":"2H2kW5YB16Vtm8BL6MfU8G"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-2","dest":"RxpQcSzFS5BVDNQjfZL2mo","role":"2","verkey":"Ec7MweMMNhELzGxbDFHsDRkCzTdwNU1HB5qHwR5ceyJ2"},"metadata":{"from":"2H2kW5YB16Vtm8BL6MfU8G"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-3","dest":"XT6icc1rXuUmKUcX3qeBib","role":"2","verkey":"HbarkGaCAj2RpApfeQuktyZyAoS71TBdqRAjqPseBkpc"},"metadata":{"from":"2H2kW5YB16Vtm8BL6MfU8G"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-4","dest":"4dwXZGbHZ2tyvsABzqYHTZ","role":"2","verkey":"2yyEWi2uPjs7SXNJbNDANNiq7vyjb5hbrTsJPU8xMLsz"},"metadata":{"from":"2H2kW5YB16Vtm8BL6MfU8G"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
