apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: university-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: university-ns
spec:
  releaseName: university-dtg
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-indy/charts/indy-domain-genesis
    sourceRef:
      kind: GitRepository
      name: flux-bevel
      namespace: flux-bevel
  values:
    metadata:
      name: university-dtg
      namespace: university-ns
    organization:
      name: university
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"FKGwzBmQ9QymDVyQydzq3A","role":"0","verkey":"8oXdTBJMTHnvtAckQpaZehvhHFZjm3PnA2UcPUHXHHaz"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"Qs39dEGhpjfn4YEanquW5m","role":"0","verkey":"E1M96KqP5YDZ64p9E5jfMzWNDzyP8HYvXMr9EjAjDeh1"},"metadata":{"from":"FKGwzBmQ9QymDVyQydzq3A"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-1","dest":"x5tUXebSYrTENHV31G4VQ","role":"2","verkey":"X2Kh8zTmFUzQmTHZcsWi8RpkeZv2mcYNMvs2VnzSZq2"},"metadata":{"from":"Qs39dEGhpjfn4YEanquW5m"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-2","dest":"N3r36T8Wv2UAUBMhCbokqH","role":"2","verkey":"CUQLDwqxYu7d7wB5VSBipCd8mZ8gx9HCUx7CSimGerJA"},"metadata":{"from":"Qs39dEGhpjfn4YEanquW5m"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-3","dest":"BdKVmy3PHtkrVpSMoQLLP4","role":"2","verkey":"6nv4DLVSWvEkzHFs2oKQb2TztR8MA2ipJBgE65mZ7wz5"},"metadata":{"from":"Qs39dEGhpjfn4YEanquW5m"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-4","dest":"69sC5HTU3gTFHmxPHWzuSk","role":"2","verkey":"3otiwxsfSA1V4GdYBpdTZRHbax8cn47PWVdFXLePQhP7"},"metadata":{"from":"Qs39dEGhpjfn4YEanquW5m"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
