apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: university-authority-trustee-vault-auth-role-binding
  namespace: university-ns
  labels:
    organization: university
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: university-authority-trustee-vault-auth
  namespace: university-ns
