apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authority-dtg
  annotations:
    fluxcd.io/automated: "false"
  namespace: authority-ns
spec:
  releaseName: authority-dtg
  interval: 1m
  chart:
   spec:
    chart: platforms/hyperledger-indy/charts/indy-domain-genesis
    sourceRef:
      kind: GitRepository
      name: flux-bevel
      namespace: flux-bevel
  values:
    metadata:
      name: authority-dtg
      namespace: authority-ns
    organization:
      name: authority
    configmap:
      domainGenesis: |-
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"2RSxdDLBTTXgxCYxHdLv5H","role":"0","verkey":"mwL9qYwN87MCsXuUo6Lm9uUMDrPU9jtCxom1NhaYneD"},"metadata":{},"type":"1"},"txnMetadata":{"seqNo":1},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"authority-trustee","dest":"KrAGaQtaru51KagCvDoKWk","role":"0","verkey":"BGowK4FDs72B2V7jbVNF4N7x3LYGoHkTyixCxd2UsgKv"},"metadata":{"from":"2RSxdDLBTTXgxCYxHdLv5H"},"type":"1"},"txnMetadata":{"seqNo":2},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-1","dest":"CcyMJir4K4gQKfTYtTkm8u","role":"2","verkey":"7LLa2fbAK7745xpvMZzeVPwhm3BLD85dtrRqdP6dnsUY"},"metadata":{"from":"KrAGaQtaru51KagCvDoKWk"},"type":"1"},"txnMetadata":{"seqNo":3},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-2","dest":"VkFHine8Uph8sq8Ch7p37C","role":"2","verkey":"GfhwkHZpJsrH62MxuCuMe9EWWWiid4Rt5m2itfYMkMJ2"},"metadata":{"from":"KrAGaQtaru51KagCvDoKWk"},"type":"1"},"txnMetadata":{"seqNo":4},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-3","dest":"4fDdNav6r7tghtTEaLk4ye","role":"2","verkey":"2zfcy8xtqpKaEWf8MJSUNoGVU5HgxBNWQGJiJqtzQm5P"},"metadata":{"from":"KrAGaQtaru51KagCvDoKWk"},"type":"1"},"txnMetadata":{"seqNo":5},"ver":"1"}
        {"reqSignature":{},"txn":{"data":{"alias":"university-steward-4","dest":"CPpuMxau2XAav9RCmgtKxP","role":"2","verkey":"7DB1ZqC4k6rEdHVHqPhwEMwgh2jfq1Gi4pVDXD53bjhj"},"metadata":{"from":"KrAGaQtaru51KagCvDoKWk"},"type":"1"},"txnMetadata":{"seqNo":6},"ver":"1"}
